In [1]:
typeof(5)

[1] "double"

In [2]:
5:5

[1] 5

In [3]:
typeof(5:5)

[1] "integer"

In [4]:
c(5)

[1] 5

In [5]:
typeof(c(5))

[1] "double"

In [6]:
typeof(c(5,))

ERROR: Error in c(5, ): 2元素是空的


In [7]:
c(5,)

ERROR: Error in c(5, ): 2元素是空的


In [8]:
v <- c(1,2,3,4,5)

In [9]:
v

[1] 1 2 3 4 5

In [10]:
v <- c(1,2,3,4,5,'c')

In [11]:
v

[1] "1" "2" "3" "4" "5" "c"

In [12]:
v <- c(1,2,3,4,5,list(1,2,3))

In [13]:
v

[[1]]
[1] 1

[[2]]
[1] 2

[[3]]
[1] 3

[[4]]
[1] 4

[[5]]
[1] 5

[[6]]
[1] 1

[[7]]
[1] 2

[[8]]
[1] 3

In [14]:
typeof(v)

[1] "list"

In [15]:
v[6]

[[1]]
[1] 1

In [16]:
m <- matrix(data=1:12, nrow = 4, ncol = 3, dimnames = list(c('r1', 'r2', 'r3', 'r4'), c('c1', 'c2', 'c3')))

In [17]:
m

c1 c2 c3
r1 1  5   9
r2 2  6  10
r3 3  7  11
r4 4  8  12

In [18]:
a <- array(data = 1:24, dim = c(3, 4, 2))

In [19]:
a

, , 1

     [,1] [,2] [,3] [,4]
[1,]    1    4    7   10
[2,]    2    5    8   11
[3,]    3    6    9   12

, , 2

     [,1] [,2] [,3] [,4]
[1,]   13   16   19   22
[2,]   14   17   20   23
[3,]   15   18   21   24

In [20]:
?I

In [22]:
c(2008, 2)

[1] 2008    2

In [23]:
ts(data = 1:8, start = c(2008, 2), frequency = 4)

     Qtr1 Qtr2 Qtr3 Qtr4
2008         1    2    3
2009    4    5    6    7
2010    8               

In [24]:
library(nutshell)

Warning message:
"package 'nutshell' was built under R version 3.4.3"Loading required package: nutshell.bbdb
Warning message:
"package 'nutshell.bbdb' was built under R version 3.4.3"Loading required package: nutshell.audioscrobbler
Warning message:
"package 'nutshell.audioscrobbler' was built under R version 3.4.3"

In [25]:
library(nutshell)

In [26]:
data(turkey.price.ts)

In [27]:
turkey.price.ts

      Jan  Feb  Mar  Apr  May  Jun  Jul  Aug  Sep  Oct  Nov  Dec
2001 1.58 1.75 1.63 1.45 1.56 2.07 1.81 1.74 1.54 1.45 0.57 1.15
2002 1.50 1.66 1.34 1.67 1.81 1.60 1.70 1.87 1.47 1.59 0.74 0.82
2003 1.43 1.77 1.47 1.38 1.66 1.66 1.61 1.74 1.62 1.39 0.70 1.07
2004 1.48 1.48 1.50 1.27 1.56 1.61 1.55 1.69 1.49 1.32 0.53 1.03
2005 1.62 1.63 1.40 1.73 1.73 1.80 1.92 1.77 1.71 1.53 0.67 1.09
2006 1.71 1.90 1.68 1.46 1.86 1.85 1.88 1.86 1.62 1.45 0.67 1.18
2007 1.68 1.74 1.70 1.49 1.81 1.96 1.97 1.91 1.89 1.65 0.70 1.17
2008 1.76 1.78 1.53 1.90                                        

In [28]:
start(turkey.price.ts)

[1] 2001    1

In [29]:
end(turkey.price.ts)

[1] 2008    4

In [30]:
frequency(turkey.price.ts)

[1] 12

In [31]:
deltat(turkey.price.ts)

[1] 0.08333333

In [32]:
m <- matrix(data = 1:12, nrow = 4, ncol = 3, dimnames = list(c('r1', 'r2', 'r3', 'r4'), c('c1', 'c2', 'c3')))

In [33]:
m

c1 c2 c3
r1 1  5   9
r2 2  6  10
r3 3  7  11
r4 4  8  12

In [34]:
attributes(m)

$dim
[1] 4 3

$dimnames
$dimnames[[1]]
[1] "r1" "r2" "r3" "r4"

$dimnames[[2]]
[1] "c1" "c2" "c3"

In [35]:
dim(m)

[1] 4 3

In [36]:
dimnames(m)

[[1]]
[1] "r1" "r2" "r3" "r4"

[[2]]
[1] "c1" "c2" "c3"

In [37]:
dimnames(m)[1]

[[1]]
[1] "r1" "r2" "r3" "r4"

In [38]:
dimnames(m)[[1]]

[1] "r1" "r2" "r3" "r4"

In [39]:
colnames(m)

[1] "c1" "c2" "c3"

In [40]:
rownames(m)

[1] "r1" "r2" "r3" "r4"

In [41]:
dim(m) <- NULL

In [42]:
m

[1]  1  2  3  4  5  6  7  8  9 10 11 12

In [43]:
a <- array(1:12, dim = c(3,4))

In [44]:
a

[,1] [,2] [,3] [,4]
[1,] 1    4    7    10  
[2,] 2    5    8    11  
[3,] 3    6    9    12

In [45]:
b <- 1:12

In [46]:
b

[1]  1  2  3  4  5  6  7  8  9 10 11 12

In [47]:
a == b

[,1] [,2] [,3] [,4]
[1,] TRUE TRUE TRUE TRUE
[2,] TRUE TRUE TRUE TRUE
[3,] TRUE TRUE TRUE TRUE

In [49]:
all.equal(a, b)

[1] "Attributes: < Modes: list, NULL >"                   
[2] "Attributes: < Lengths: 1, 0 >"                       
[3] "Attributes: < names for target but not for current >"
[4] "Attributes: < current is not list-like >"            
[5] "target is matrix, current is numeric"

In [50]:
identical(a, b)

[1] FALSE

In [51]:
attributes(b)

NULL

In [52]:
dim(b)

NULL

In [53]:
dim(b) <- c(3,4)

In [54]:
b

[,1] [,2] [,3] [,4]
[1,] 1    4    7    10  
[2,] 2    5    8    11  
[3,] 3    6    9    12