In [2]:
2*1024

[1] 2048

In [3]:
2^1023

[1] 8.988466e+307

In [4]:
0x1

[1] 1

In [5]:
0xFFFF

[1] 65535

In [6]:
1:1

[1] 1

In [7]:
1:2

[1] 1 2

In [8]:
2^1024

[1] Inf

In [9]:
-1+4i

[1] -1+4i

In [10]:
x1 <- 1

In [11]:
X1 <- 1

In [12]:
41 %% 20

[1] 1

In [13]:
v <- c(1, 2, 3, 4, 5, 6, 7 ,8)

In [14]:
dim(v)

NULL

In [15]:
?dim

In [16]:
dim(v) <- c(2 ,4)

In [17]:
v

[,1] [,2] [,3] [,4]
[1,] 1    3    5    7   
[2,] 2    4    6    8

In [19]:
f <- function() {u <-1; v <- 2; u + v}

In [20]:
f

function() {u <-1; v <- 2; u + v}

In [21]:
f()

[1] 3

In [22]:
{u <-1; v <- 2; u + v}

[1] 3

In [23]:
u

[1] 1

In [24]:
v

[1] 2

In [25]:
?function

ERROR: Error in parse(text = x, srcfile = src): <text>:2:0: unexpected end of input
1: ?function
   ^


In [26]:
help(function)

ERROR: Error in parse(text = x, srcfile = src): <text>:1:14: 意外的')'
1: help(function)
                 ^


In [27]:
switcheroo.if.then <- function(x) {
    if (x == 'a')
        'alligator'
    else if (x == 'b')
        'bear'
    else if (x == 'c')
        'camel'
    else
        'moose'
}

In [28]:
switcheroo.swith <- function(x) {
    switch(x, 
          a='alligator',
          b='bear',
          c='camel',
          'moose')
}

In [29]:
switcheroo.if.then('a')

[1] "alligator"

In [30]:
switcheroo.if.then('f')

[1] "moose"

In [31]:
switcheroo.swith('a')

[1] "alligator"

In [32]:
switcheroo.swith('f')

[1] "moose"

In [34]:
i <- 5
repeat {
    if (i > 25) break else {
        print(i);
        i <- i + 5
    }
}

[1] 5
[1] 10
[1] 15
[1] 20
[1] 25


In [35]:
i <- 5
while (i <= 25) {
    print(i);
    i <- i + 5
}

[1] 5
[1] 10
[1] 15
[1] 20
[1] 25


In [36]:
for (i in seq(from = 5, to = 25, by = 5)) print(i)

[1] 5
[1] 10
[1] 15
[1] 20
[1] 25


In [37]:
v <- 100:119

In [38]:
v

[1] 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118
[20] 119

In [39]:
v[5]

[1] 104

In [40]:
v[1:5]

[1] 100 101 102 103 104

In [41]:
v[c(1, 6, 11, 16)]

[1] 100 105 110 115

In [42]:
v[[3]]

[1] 102

In [43]:
typeof(v[[3]])

[1] "integer"

In [44]:
typeof(v[3])

[1] "integer"

In [45]:
v[-15:-1]

[1] 115 116 117 118 119

In [46]:
-1:-15

[1]  -1  -2  -3  -4  -5  -6  -7  -8  -9 -10 -11 -12 -13 -14 -15

In [47]:
-15:-1

[1] -15 -14 -13 -12 -11 -10  -9  -8  -7  -6  -5  -4  -3  -2  -1

In [48]:
l <- list(a=1, b=2, c=3, d=4, e=5, f=6, g=7, h=8, i=9, j=10)

In [49]:
l

$a
[1] 1

$b
[1] 2

$c
[1] 3

$d
[1] 4

$e
[1] 5

$f
[1] 6

$g
[1] 7

$h
[1] 8

$i
[1] 9

$j
[1] 10

In [50]:
l[1:3]

$a
[1] 1

$b
[1] 2

$c
[1] 3

In [51]:
l[1:3]$a

[1] 1

In [52]:
l[-7:-1]

$h
[1] 8

$i
[1] 9

$j
[1] 10

In [53]:
m <- matrix(data=c(101:112), nrow = 3, ncol = 4)

In [54]:
m

[,1] [,2] [,3] [,4]
[1,] 101  104  107  110 
[2,] 102  105  108  111 
[3,] 103  106  109  112

In [55]:
m[3]

[1] 103

In [56]:
m[5]

[1] 105

In [57]:
m[3,4]

[1] 112

In [58]:
m[1:2, 1:2]

[,1] [,2]
[1,] 101  104 
[2,] 102  105

In [59]:
m[3,]

[1] 103 106 109 112

In [60]:
m[1:2,]

[,1] [,2] [,3] [,4]
[1,] 101  104  107  110 
[2,] 102  105  108  111

In [61]:
a <- array(data=c(101:124), dim=c(2, 3, 4))

In [62]:
a

, , 1

     [,1] [,2] [,3]
[1,]  101  103  105
[2,]  102  104  106

, , 2

     [,1] [,2] [,3]
[1,]  107  109  111
[2,]  108  110  112

, , 3

     [,1] [,2] [,3]
[1,]  113  115  117
[2,]  114  116  118

, , 4

     [,1] [,2] [,3]
[1,]  119  121  123
[2,]  120  122  124

In [63]:
a[1,1,]

[1] 101 107 113 119

In [64]:
class(a[1,1,])

[1] "integer"

In [65]:
a[1,,]

[,1] [,2] [,3] [,4]
[1,] 101  107  113  119 
[2,] 103  109  115  121 
[3,] 105  111  117  123

In [66]:
class(a[1,,])

[1] "matrix"

In [72]:
a[1:2,1:2,1:2]
typeof(a[1:2,1:2,1:2])

, , 1

     [,1] [,2]
[1,]  101  103
[2,]  102  104

, , 2

     [,1] [,2]
[1,]  107  109
[2,]  108  110

[1] "integer"

In [68]:
class(a[1:2,1:2,1:2])

[1] "array"

In [70]:
class(a[1:2,1:2,1:2,drop=FALSE])

[1] "array"

In [73]:
m[1] <- 1000

In [74]:
m

[,1] [,2] [,3] [,4]
[1,] 1000 104  107  110 
[2,]  102 105  108  111 
[3,]  103 106  109  112

In [75]:
m[1:2,1:2] <- matrix(c(1001:1004), nrow = 2, ncol = 2)

In [76]:
m

[,1] [,2] [,3] [,4]
[1,] 1001 1003 107  110 
[2,] 1002 1004 108  111 
[3,]  103  106 109  112

In [77]:
v <- 1:12

In [78]:
v

[1]  1  2  3  4  5  6  7  8  9 10 11 12

In [79]:
v[15]

[1] NA

In [80]:
v

[1]  1  2  3  4  5  6  7  8  9 10 11 12

In [81]:
v[15] <- 15

In [82]:
v

[1]  1  2  3  4  5  6  7  8  9 10 11 12 NA NA 15

In [83]:
rep(c(TRUE, FALSE), 10)

[1]  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE
[13]  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE

In [84]:
v[rep(c(TRUE, FALSE), 10)]

[1]  1  3  5  7  9 11 NA 15 NA NA

In [85]:
l[l>7]

$h
[1] 8

$i
[1] 9

$j
[1] 10

In [86]:
v[c(TRUE,FALSE,FALSE)]

[1]  1  4  7 10 NA

In [87]:
l[c('a','b','c')]

$a
[1] 1

$b
[1] 2

$c
[1] 3

In [88]:
dairy <- list(milk='1 gallon', butter='1 pound', eggs=12)

In [89]:
dairy

$milk
[1] "1 gallon"

$butter
[1] "1 pound"

$eggs
[1] 12

In [90]:
dairy$milk

[1] "1 gallon"

In [91]:
dairy[['milk']]

[1] "1 gallon"

In [92]:
dairy[['mil']]

NULL

In [93]:
dairy[['mil',exact=FALSE]]

[1] "1 gallon"

In [95]:
dairy[1]

$milk
[1] "1 gallon"

In [96]:
dairy[[1]]

[1] "1 gallon"

In [97]:
fruit <- list(apples=6, oranges=3, bananas=10)

In [98]:
shopping.list <- list(dairy=dairy, fruit=fruit)

In [99]:
shopping.list

$dairy
$dairy$milk
[1] "1 gallon"

$dairy$butter
[1] "1 pound"

$dairy$eggs
[1] 12


$fruit
$fruit$apples
[1] 6

$fruit$oranges
[1] 3

$fruit$bananas
[1] 10

In [100]:
shopping.list[[c('dairy', 'milk')]]

[1] "1 gallon"

In [101]:
shopping.list[[c(1,2)]]

[1] "1 pound"